servers:
  google: &google-server
    host: talk.google.com
    port: 5222
development: &defaults
  chat_izap:
    <<: *google-server
    login: chat@izap.com.br
    password: euamoocussiol
  heitor_izap:
    <<: *google-server
    login: heitor.salazar@izap.com.br
    password: 74193456
production:
  chat_izap:
    <<: *google-server
    login: chat@izap.com.br
    password: euamoocussiol
  chat_producao:
    <<: *google-server
    login: chat-producao@izap.com.br
    password: modificar
  chat_projetos:
    <<: *google-server
    login: chat-projetos@izap.com.br
    password: modificar
  chat_suporte:
    <<: *google-server
    login: chat-suporte@izap.com.br
    password: modificar
staging:
  <<: *defaults