servers:
  google: &google-server
    host: talk.google.com
    port: 5222
  talkr: &talkr-server
    host: talkr.im
development: &defaults
  heitor_gmail:
    <<: *google-server
    login: heitorsalazar@gmail.com.br
    password: )74193456((74193456)
production:
  indefinidomatic:
    <<: *talkr-server
    login: indefinidomatic@talkr.im
    password: shieloovoogo
staging:
  <<: *defaults
  heitor_woollu:
    <<: *google-server
    login: heitorsalazar@woollu.com
    password: )74193456((74193456)
